name: Testing stuff

on:
  push:
    branches:
      - test-workflow

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined commit messages
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$JOINED_MESSAGES"
      - name: contains skip
        env:
          SKIP: ${{ toJson(contains(join(github.event.commits.*.message), '#skip')) }}
        run: echo "$SKIP"
      - name: not skipped
        env:
          NOT_SKIPPED: ${{ github.event_name == 'push' && env.SKIP == 'false' }}
          SKIP_FALSE: ${{ env.SKIP }}
        run: echo " not skipped < $NOT_SKIPPED > | skip is false < $SKIP_FALSE >"
      - name: if not skipped
        if: ${{ github.event_name == 'push' && env.SKIP == false }}
        run: echo "I should deploy and tag"
