name: Testing stuff

on:
  push:
    branches:
      - test-workflow

jobs:
  test_job_1:
    runs-on: ubuntu-20.04
    outputs:
      deploy_and_tag: ${{ steps.simple_deploy.outputs.deploy }}
    steps:
      - id: simple_deploy
      - uses: actions/checkout@v2
      - name: joined commit messages
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$JOINED_MESSAGES"
      - name: should deploy and tag if not '#skip'
        env:
          NOT_SKIP: ${{ (github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')) }}
        run: |
          echo "DEPLOY_AND_TAG=${NOT_SKIP}" >> $GITHUB_ENV
          echo "DEPLOY_AND_TAG set to ${NOT_SKIP}"
          echo "::set-output name=deploy::${NOT_SKIP}"
      - name: deploy if true
        if: env.DEPLOY_AND_TAG == 'true'
        run: echo "I deploy"
  test_job_2:
    needs: [test_job_1]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: deploy_and_tag output
        env:
          TEST_DEPLOY_AND_TAG: ${{ needs.test_job_1.outputs.deploy_and_tag }}
        run: echo "deploy and tag output < ${TEST_DEPLOY_AND_TAG} >"
      - name: use deploy and tag env
        if: ${{ needs.test_job_1.outputs.deploy_and_tag == 'true' }}
        run: echo "I tag"
