name: Testing stuff

on:
  push:
    branches:
      - test-workflow

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined commit messages
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$JOINED_MESSAGES"
      - name: contains skip
        env:
          CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: |
          echo "skip=${CONTAINS_SKIP}" >> $GITHUB_ENV
          echo "set skip to ${CONTAINS_SKIP}"
      - name: is push
        env:
          IS_PUSH: ${{ github.event_name == 'push' }}
        run: |
          echo "push=${IS_PUSH}" >> $GITHUB_ENV
          echo "set push to ${IS_PUSH}"
      - name: if not skipped
        if: env.push && !env.skip
        run: echo "I should deploy and tag"
