name: Testing stuff

on:
  push:
    branches:
      - test-workflow

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined commit messages
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$JOINED_MESSAGES"
      - name: contains skip
        env:
          CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
          IS_PUSH: ${{ github.event_name == 'push' }}
        run: |
          if ${CONTAINS_SKIP} == true; then
            echo "deploy=false" >> $GITHUB_ENV
            echo "deploy set to false"
          else
            echo "deploy=${IS_PUSH}" >> $GITHUB_ENV
            echo "deploy set to ${IS_PUSH}"
          fi
      - name: if not skipped
        if: env.deploy
        run: echo "I should deploy and tag"
